config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  scope controller: :landing do
    get "/about" => :about, as: :about
    get "/contact" => :contact_us, as: :contact
    post "/feedback" => :create_feedback, as: :feedback
  end

  scope controller: :session do
    get "/login" => :new, as: :login
    get "/logout" => :destroy, as: :logout
    post "/session" => :create, as: :session
  end

  scope "/users", controller: :users do
    get "/signup" => :new, as: :signup
    get "/bookings" => :past_bookings, as: :past_bookings
    post "/" => :create
  end

  scope "/flights", controller: :flights do
    post "/search" => :search, as: :search_flights
    get "/seats_available" => :seats_available
  end

  scope "/bookings", controller: :bookings do
    post "/book" => :book, as: :book
    get "/search" => :search, as: :search_booking
    post "/" => :retrieve, as: :retrieve_booking
    get "/payment" => :payment, as: :payment
    post "/confirm" => :confirm, as: :confirm_book
    put "/:reference_number" => :update
    delete "/:reference_number" => :destroy
    get "/payment/:flight_id" => :validate_payment, as: :validate_payment
  end
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  has_many :bookings
  belongs_to :from_airport, class_name: "Airport"
  belongs_to :to_airport, class_name: "Airport"

  def self.search(departs, arrives, date, total_passengers)
    sql_query = "date >= ? and seats_available > ?"
    flights = where(sql_query, date, total_passengers)
    flights.uniq(&:date).select do |flight|
      flight.from_airport.name == departs[0..-7] &&
        flight.to_airport.name == arrives[0..-7]
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  protect_from_forgery except: [:search, :seats_available]

  def search
    @retrieved_flights = Flight.search(
      params[:departs],
      params[:arrives],
      search_date,
      total_passengers
    )

    render format: :js
  end

  def seats_available
    flight = Flight.find_by(id: session[:flight_id])

    if flight
      render json: flight.to_json(only: [:seats_available])
    else
      render json: { error: true }
    end
  end

  private

  def total_passengers
    data = {
      total_children: params[:children],
      total_adults: params[:adults],
      total_infants: params[:infants]
    }
    store_passengers_info
    data.values.map(&:to_i).inject(0) { |sum, x| sum + x }
  end

  def store_passengers_info
    session[:passengers] = { class_level: params[:grade] }
  end

  def search_date
    Time.zone.parse(params[:date])
  end
end

app/views/flights/_retrieved_flights.html.erb
<% if @retrieved_flights.empty? %>
  <div class="ui message">
    <div class="header">
      No Flight Found
    </div>
    <p>Sorry, No flight was found with your search criteria</p>
  </div>
  <div class="ui center aligned grid">
    <%= link_to root_path, class: "ui left floated small teal button" do %>
      <i class="left arrow icon"></i>
      Go Back
    <% end %>
  </div>
<% else %>
  <h3 class="ui header"> Flights Available </h3>
  <%= form_tag book_path, method: "post", class: "ui form", remote: true do %>
    <table class="ui celled padded stripped definition table">
      <thead>
        <tr>
          <th></th>
          <th>Departure</th>
          <th>Arrival</th>
          <th>Stops</th>
          <th>Date</th>
          <th>Flight</th>
        </tr>
      </thead>
      <tbody>
        <% @retrieved_flights.each_with_index do |flight, index| %>
          <tr>
            <td class="collapsing">
              <%= radio_button_tag "selected_flight", flight.id, checked=false, required: true %> <%= label_tag %>
            </td>
            <td><%= flight.from_airport.name %></td>
            <td><%= flight.to_airport.name %></td>
            <td><%= flight.stops %></td>
            <td><%= flight.date.strftime("%B %d, %Y") %></td>
            <td><%= flight.plane_name %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot class="full-width">
        <tr>
          <th></th>
          <th colspan="4">
            <%= link_to root_path, class: "ui left floated small teal button" do %>
              <i class="left arrow icon"></i>
              Go Back
            <% end %>
            <%= submit_tag "Book Now", class: "ui right floated small primary button" do %>
              <i class="right arrow icon"></i>
            <% end %>
          </th>
        </tr>
      </tfoot>
    </table>
  <% end %>
<% end %>

app/views/flights/search.js.erb
$(document).ready(function(){
  $("#progress-container").html("<%= escape_javascript(render partial: 'retrieved_flights') %>")
  $(".step").removeClass("active")
  $("#select-flight").addClass("active")
  $("#progress-container").removeClass("loading");
})