config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  scope controller: :landing do
    get "/about" => :about, as: :about
    get "/contact" => :contact_us, as: :contact
    post "/feedback" => :create_feedback, as: :feedback
  end

  scope controller: :session do
    get "/login" => :new, as: :login
    get "/logout" => :destroy, as: :logout
    post "/session" => :create, as: :session
  end

  scope "/users", controller: :users do
    get "/signup" => :new, as: :signup
    get "/bookings" => :past_bookings, as: :past_bookings
    post "/" => :create
  end

  scope "/flights", controller: :flights do
    post "/search" => :search, as: :search_flights
    get "/seats_available" => :seats_available
  end

  scope "/bookings", controller: :bookings do
    post "/book" => :book, as: :book
    get "/search" => :search, as: :search_booking
    post "/" => :retrieve, as: :retrieve_booking
    get "/payment" => :payment, as: :payment
    post "/confirm" => :confirm, as: :confirm_book
    put "/:reference_number" => :update
    delete "/:reference_number" => :destroy
    get "/payment/:flight_id" => :validate_payment, as: :validate_payment
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :flight

  has_many :passengers, dependent: :destroy

  validates :reference_number, presence: true, uniqueness: true
  validates :class_level, presence: true

  def add_passengers(passenger_params)
    %w(adult child infant).each do |type|
      create_passengers(passenger_params[type], type) if passenger_params[type]
    end
  end

  def create_passengers(passenger_param, type)
    passenger_param.each do |passenger|
      passenger = passenger.merge(age_grade: type.capitalize)
      passengers << Passenger.create(passenger)

      save
    end
  end

  def update_passengers(passengers_param)
    passengers.destroy_all
    add_passengers(passengers_param)
  end

  def allocate_flight(flight)
    total_passengers = passengers.not_infant.count
    seats_available = flight.seats_available - total_passengers
    flight.update(seats_available: seats_available)
    update(flight: flight)
  end

  def self.create_and_allocate(options)
    booking = create(options.slice(:reference_number, :class_level))
    booking.add_passengers(options[:booking_params])
    booking.allocate_flight(options[:flight])
    booking.update(user: options[:user]) if booking

    booking
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include Bookings
  before_action :set_booking, only: [:retrieve, :destroy, :update]
  protect_from_forgery except: [:retrieve, :destroy]

  def confirm
    session[:booking_params] = booking_params
    @booking_params = booking_params

    render format: :js
  end

  def book
    session[:flight_id] ||= params[:selected_flight]

    render format: :js
  end

  def payment
    payment_service = instantiate_payment_service
    response = payment_service.make_payment
    session[:token] = response.token

    redirect_to response.redirect_uri
  end

  def validate_payment
    if params[:token] == session[:token]
      selected_flight = Flight.find(session[:flight_id])
      create_booking(selected_flight, params[:token])
    else
      flash[:notice] = invalid_payment
    end
  end

  def retrieve
    render format: :js
  end

  def search
  end

  def update
    @booking.update_passengers(booking_params)
    UserMailer.update_reservation(@booking.id).deliver_now if @booking.user
    redirect_to search_booking_path, notice: booking_success
  end

  def destroy
    UserMailer.delete_reservation(@booking.id).deliver_now if @booking.user
    @booking.destroy

    render json: { success: true }
  end

  private

  def set_booking
    @booking = Booking.find_by(reference_number: params[:reference_number])
  end

  def instantiate_payment_service
    selected_flight = Flight.find(session[:flight_id])

    PaymentService.new(
      selected_flight: selected_flight,
      validate_url: validate_payment_url(selected_flight),
      contact_url: contact_url,
      total_cost: session[:total_cost]
    )
  end

  def booking_params
    passenger_fields = %w(first_name last_name email)
    params.permit(
      adult: passenger_fields,
      child: passenger_fields,
      infant: passenger_fields
    )
  end
end

app/controllers/concerns/bookings.rb
module Bookings
  def create_booking(flight, reference)
    booking_params = session[:booking_params]
    class_level = session[:passengers]["class_level"]
    @booking = Booking.create_and_allocate(
      flight: flight,
      reference_number: reference,
      class_level: class_level,
      booking_params: booking_params,
      user: current_user
    )
    UserMailer.booking_success(@booking.id).deliver_now
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def calculate_flight_fare(booking_params)
    passengers = []
    allowed_passengers = %w(adult child infant)
    iterate_passengers(passengers, booking_params, allowed_passengers)
    session[:total_cost] = estimate_flight_fare(passengers, booking_grade)
  end

  def booking_grade
    session[:passengers]["class_level"].to_sym
  end

  def adult_fare
    fares[booking_grade]
  end

  def child_fare
    fares[booking_grade]
  end

  def infant_fare
    0
  end

  def estimate_flight_fare(passengers, grade = nil)
    class_level = grade.to_sym || booking_grade
    total_cost = 0
    passengers.each do |passenger|
      unless passenger.age_grade == "Infant"
        total_cost += fares[class_level]
      end
    end
    total_cost
  end

  def iterate_passengers(passengers, params, allowed_passengers)
    allowed_passengers.each do |allowed_passenger|
      allowed_passenger = allowed_passenger.to_sym
      next unless params[allowed_passenger]
      params[allowed_passenger].each do |passenger|
        build_passengers(passengers, passenger, allowed_passenger.capitalize)
      end
    end
  end

  def build_passengers(passengers, params, type)
    params = params.merge(age_grade: type)
    passengers << Passenger.new(params)
  end

  def fares
    {
      Economy: 1000,
      Business: 5000
    }
  end
end

app/views/bookings/_booking_notification.html.erb
<% if flash[:notice] %>
  <div class="header">
    Payment Error!
   </div>
   <p>Your Payment is not valid</p>
<% else %>
   <div class="header">
    Congratulations!!!
   </div>
  <p> Your Flight from <%= @booking.flight.from_airport.name %> to  <%= @booking.flight.to_airport.name %> has been successfully  booked.</p>
  <p>Your Booking reference number is <strong> <%= @booking.reference_number %> </strong> </p>

  <%= link_to root_path, class: "ui teal basic button" do %>
    <i class="home icon"></i>
    Return Home
  <% end %>
<% end %>

app/views/bookings/_booking_reference.html.erb
<% if @booking %>
  <%= render partial: "modals/edit_reservation_modal", locals: { booking: @booking } %>
  <h3 class="ui top attached header">
    Booking #<%= "#{@booking.reference_number}" %>
  </h3>
  <div class="ui attached segment">
    <p><h4>Departing Airport: </h4><%= @booking.flight.from_airport.name %></p>
    <p><h4>Arriving Airport: </h4><%= @booking.flight.to_airport.name %></p>
    <p><h4>Number of passengers: </h4><%= @booking.passengers.count %> <button class="custom-button" onclick="showPassenger()">View</button></p>
    <p><h4>Departure Date: </h4> <%= @booking.flight.date.strftime("%B %d, %Y") %> </p>
    <p><h4>Total Flight Fare: </h4> $<%= estimate_flight_fare(@booking.passengers, @booking.class_level) %></p>
    <div class="ui center aligned grid">
    <% if @booking.user %>
      <div class="ui buttons">
        <button class="ui basic red button" id="cancel-reservation" onclick="deleteConfirmDialog('<%= @booking.reference_number %>')">Cancel Reservation</button>
        <div class="or"></div>
        <button class="ui positive button" onclick="editReservation()">Edit Reservation</button>
      </div>
    <% end %>
      
    </div>
  </div>
<% else %>
  <div class="ui message">
    <div class="header">
      No record Found
    </div>
    <p>We have searched our records and no booking reference number matches <b> <%= @reference_number %> </b> </p>
  </div>
<% end %>

app/views/bookings/_confirm_booking.html.erb
<div class="ui form">
  <a class="ui blue ribbon label" onclick="retrieveBookingInfo()">Edit Information</a>
  <h2 class="ui dividing header">Your Booking Information</h2>
   
  <% if @booking_params["adult"] %>
    <% @booking_params["adult"].each.with_index(1) do |adult, index|  %>
      <h3 class="ui dividing header">Adult Passenger <%= index %> Information</h2>
      <p>Name: <span> <%= adult["first_name"] + " " + adult["last_name"] %> </span></p>
      <p>Fee: <span><%= "$#{adult_fare}" %></span></p>
    <% end %>
  <% end %>

  <% if @booking_params["child"] %>
    <% @booking_params["child"].each.with_index(1) do |child, index|  %>
      <h3 class="ui dividing header">Child Passenger <%= index %> Information</h2>
      <p>Name: <span> <%= child["first_name"] + " " + child["last_name"] %> </span></p>
      <p>Fee: <span><%= "$#{child_fare}" %></span></p>
    <% end %>
  <% end %>


  <% if @booking_params["infant"] %>
    <% @booking_params["infant"].each.with_index(1) do |infant, index|  %>
      <h3 class="ui dividing header">Infant Passenger <%= index %> Information</h2>
      <p>Name: <span> <%= infant["first_name"] + " " + infant["last_name"] %> </span></p>
      <p>Fee: <span><%= "$#{infant_fare}" %></span></p>
    <% end %>
  <% end %>

  <h2 class="ui dividing header">Flight Fare</h2>
  <p>Total Cost: <span><%= "$#{calculate_flight_fare(@booking_params)}" %></span></p>

  <%= link_to payment_path do %>
    <div class="ui center aligned grid">
      <button class="ui teal button">Ok, I am ready to make payment</button>
    </div>
  <% end %>
</div>

app/views/bookings/_passenger_booking_reference.html.erb
<% if @booking %>
  <% @booking.passengers.each.with_index(1) do |passenger, index| %>
    <div class="item">
      <%= "#{index}. #{passenger.first_name} #{passenger.last_name} (#{passenger.age_grade})" %>
    </div>
  <% end %>
<% end %>

app/views/bookings/_past_bookings_link.html.erb
<% if current_user %>
  <%= link_to past_bookings_path(current_user), class: "ui blue basic button" do %>
    <i class="suitcase icon"></i>
    View Bookings
  <% end %>
<% end %>

app/views/bookings/book.js.erb
$(document).ready(function(){
  $("#progress-container").html("<%= escape_javascript(render partial: 'forms/book_flight') %>");
  $(".step").removeClass("active");
  $("#book-flight").addClass("active");
  $('.ui.floating.dropdown').dropdown({on: 'hover', direction: 'upward'});
  $('#dropDown').click(function(){
    var no_of_passengers = $('.custom-form').length + 1;
    
    $.when(isFlightBookable()).then(function(res){
      if (res.seats_available >= no_of_passengers){
        var type = $('.ui.floating.dropdown').dropdown('get value');
        $('#form-holder').append(passengerFormString(type));
      }
      else{
        toastr.info("Sorry! The flight cannot contain this passenger", "Flight Occupied!");
      }

    }, function(res){
      toastr.error("An Error occured while trying to retrieve the flight information", "Error!");
    })
  })
})

app/views/bookings/confirm.js.erb
$(document).ready(function(){
  $("#progress-container").html("<%= escape_javascript(render partial: 'confirm_booking') %>");
  $(".progress-container").removeClass("centered grid");
  $(".progress-container").addClass("container");
  $(".step").removeClass("active");
  $("#confirm-flight").addClass("active");
})

app/views/bookings/retrieve.js.erb
$(document).ready(function(){
  $("#search-result-container").html("<%= escape_javascript(render partial: 'booking_reference') %>");
  $("#passenger-list").html("<%= escape_javascript(render partial: 'passenger_booking_reference') %>");
})

app/views/bookings/search.html.erb
<%= render partial: "notice" %>
<%= render partial: "header" %>
  <div class="ui modal" id="passengers-modal">
    <div class="header">Passengers</div>
      <div class="content">
        <p>
          <div class="ui list" id="passenger-list">
          </div>
        </p>
      </div>
  </div>

  <div class="ui centered grid">
    <div class="ui container">
       <h1 class="ui horizontal divider header">
        <i class="search icon"></i>
        Search Bookings
      </h1>
      <%= form_tag retrieve_booking_path, method: "post", remote: true do %>
        <div class="ui fluid icon input">
          <%= text_field_tag :reference_number, nil, placeholder: "Search Bookings via reference number...", required: true %>
          <i class="search icon"></i>
        </div><br/>
        <%= submit_tag "Search Bookings", class: "ui teal button" %>
      <% end %>
    </div>
  </div>
  <div class="ui container" id="search-result-container">
  </div>
  <%= render partial: "modals/confirm_delete_modal" %>
<%= render partial: "footer" %>

app/views/bookings/validate_payment.html.erb
<%= render "header" %>
  <div class="ui middle aligned centered grid">
    <div class="ui container">
      <div class="ui icon message">
        <i class="gift icon"></i>
        <div class="content">
          <%= render partial: 'booking_notification' %>
          <%= render partial: 'past_bookings_link' %>
        </div>
      </div>
    </div>
  </div>
<%= render 'footer' %>