config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  scope controller: :landing do
    get "/about" => :about, as: :about
    get "/contact" => :contact_us, as: :contact
    post "/feedback" => :create_feedback, as: :feedback
  end

  scope controller: :session do
    get "/login" => :new, as: :login
    get "/logout" => :destroy, as: :logout
    post "/session" => :create, as: :session
  end

  scope "/users", controller: :users do
    get "/signup" => :new, as: :signup
    get "/bookings" => :past_bookings, as: :past_bookings
    post "/" => :create
  end

  scope "/flights", controller: :flights do
    post "/search" => :search, as: :search_flights
    get "/seats_available" => :seats_available
  end

  scope "/bookings", controller: :bookings do
    post "/book" => :book, as: :book
    get "/search" => :search, as: :search_booking
    post "/" => :retrieve, as: :retrieve_booking
    get "/payment" => :payment, as: :payment
    post "/confirm" => :confirm, as: :confirm_book
    put "/:reference_number" => :update
    delete "/:reference_number" => :destroy
    get "/payment/:flight_id" => :validate_payment, as: :validate_payment
  end
end

app/views/forms/_book_flight.html.erb
<%= form_tag confirm_book_path, method: "post", class: "ui form", remote: true do %>
  <h4 class="ui dividing header">Please provide your information</h4>
  <div class="two fields">
    <div class="field">
      <%= label_tag :first_name, "First Name" %>
      <%= show_first_name %>
    </div>

    <div class="field">
      <%= label_tag :last_name, "Last Name" %>
      <%= show_last_name %>
    </div>
  </div>

  <div class="two fields">
    <div class="eight wide field">
      <%= label_tag :email, "Email" %>
      <%= show_email %>
    </div>
  </div>

  <div id="form-holder"></div>

  <div class="ui center aligned grid">
    <%= submit_tag "Submit", class: "ui basic blue button" %>
  </div>

  <div class="ui center aligned grid">
    <div class="ui teal buttons">
      <div class="ui button" id="dropDown">Add Passenger</div>
      <div class="ui floating dropdown icon button">
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item">Adult</div>
          <div class="item"> Child</div>
          <div class="item">Infant</div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/forms/_contact_us.html.erb
<%= form_tag feedback_path, method: "post", class: "ui form" do %>
  <h4 class="ui dividing header">Please provide your information</h4>
  <div class="two fields">
    <div class="field">
      <%= label_tag :first_name, "First Name" %>
      <%= show_first_name %>
    </div>

    <div class="field">
      <%= label_tag :last_name, "Last Name" %>
      <%= show_last_name %>
    </div>
  </div>

  <div class="two fields">
    <div class="eight wide field">
      <%= label_tag :email, "Email" %>
      <%= show_email %>
    </div>

    <div class="eight wide field">
      <%= label_tag :phone_number, "Phone Number" %>
      <%= text_field_tag :phone_number, nil, placeholder: "(+234) 734452890" %>
    </div>
  </div>

  <div class="twelve wide field">
    <%= label_tag :comment, "Drop Your Comment" %>
    <%= text_area_tag :comment, nil, required: true %>
  </div>
 
  <%= submit_tag "Submit", class: "ui basic blue button" %>
<% end %>

app/views/forms/_login.html.erb
<%= form_tag session_path, method: "post", class: check_login do %>
  <div class="ui stacked segment">
    <div class="field">
      <div class="ui left icon input">
        <i class="user icon"></i>
        <%= text_field_tag :email, nil, placeholder: "Email address", required: true %>
      </div>
    </div>
    <div class="field">
      <div class="ui left icon input">
        <i class="lock icon"></i>
        <%= password_field_tag :password, nil, placeholder: "Password", required: true  %>
      </div>
    </div>
    <%= submit_tag "Login", class: "ui fluid large teal submit button" %>
  </div>

  <div class="ui error message">
   <%= flash[:errors] %>
  </div>

<% end %>

app/views/forms/_search_flight.html.erb
<%= form_tag search_flights_path,  method: "post", class: "ui form", remote: true do %>
  <h4 class="ui dividing header">Search Flights</h4>
  <div class="three fields">
    <div class="field">
      <%= label_tag :departs, "Departs" %>
      <%= select_tag :departs, options_for_select(@airport_names), class: "ui search fluid dropdown" %>
    </div>

    <div class="field">
      <%= label_tag :arrives, "Arrives" %>
      <%= select_tag :arrives, options_for_select(@airport_names), class: "ui search fluid dropdown" %>
    </div>

    <div class="field">
      <%= label_tag :grade, "Class" %>
      <%= select_tag :grade, options_for_select([["Economy", "Economy"], ["Business", "Business"]]), class: "ui search fluid dropdown" %>
    </div>
  </div>

  <div class="six wide field">
    <%= label_tag :date, "Date" %>
    <%= date_field_tag "date", "" %>
  </div>
  
  <h4 class="ui dividing header">Passengers</h4>
  <div class="three fields">
    <div class="field">
      <%= label_tag :adults, "Number of Adults(12+)" %>
      <%= select_tag :adults, options_for_select(0..6), class: "ui fluid dropdown" %>
    </div>

    <div class="field">
      <%= label_tag :children, "Number of Children (age 2-11)" %>
      <%= select_tag :children, options_for_select(0..6), class: "ui fluid dropdown" %>
    </div>

    <div class="field">
      <%= label_tag :infants, "Number of Infants (under 2)" %>
      <%= select_tag :infants, options_for_select(0..2), class: "ui fluid dropdown" %>
    </div>
  </div>
  <%= submit_tag "Search", class: "ui basic blue button", onclick: "validateFields(event)" do %>
    <i class="search icon"></i>
  <% end %>

<% end %>

app/views/forms/_sign_up.html.erb
<%= form_tag "/users", method: "post", class: "ui form" do %>
  <h4 class="ui dividing header">Please provide your information</h4>
  <div class="two fields">
    <div class="field">
      <%= label_tag :first_name, "First Name" %>
      <%= text_field_tag :first_name, nil, placeholder: "First Name", required: true %>
    </div>

    <div class="field">
      <%= label_tag :last_name, "Last Name" %>
      <%= text_field_tag :last_name, nil, placeholder: "Last Name", required: true  %>
    </div>
  </div>

  <div class="two fields">
    <div class="eight wide field">
      <%= label_tag :email, "Email" %>
      <%= text_field_tag :email, nil, placeholder: "E.g johndoe@gmail.com", required: true  %>
    </div>

    <div class="eight wide field">
      <%= label_tag :phone, "Phone Number" %>
      <%= text_field_tag :phone, nil, placeholder: "(+234) 74460478", required: true  %>
    </div>
  </div>

  <div class="eight wide field">
    <%= label_tag :phone, "Gender" %>
    <%= select_tag :gender, options_for_select([["Male", "Male"], ["Female", "Female"]]), class: "ui fluid dropdown" %>
  </div>

  <div class="two fields">
    <div class="eight wide field">
      <%= label_tag :password, "Password" %>
      <%= password_field_tag :password, nil, required: true %>
    </div>
   
    <div class="eight wide field">
      <%= label_tag :password_confirmation, "Confirm Password" %>
      <%= password_field_tag :password_confirmation, nil, required: true %>
    </div>
  </div>

  <%= submit_tag "Create Account", class: "ui basic blue button" %>
<% end %>