config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  scope controller: :landing do
    get "/about" => :about, as: :about
    get "/contact" => :contact_us, as: :contact
    post "/feedback" => :create_feedback, as: :feedback
  end

  scope controller: :session do
    get "/login" => :new, as: :login
    get "/logout" => :destroy, as: :logout
    post "/session" => :create, as: :session
  end

  scope "/users", controller: :users do
    get "/signup" => :new, as: :signup
    get "/bookings" => :past_bookings, as: :past_bookings
    post "/" => :create
  end

  scope "/flights", controller: :flights do
    post "/search" => :search, as: :search_flights
    get "/seats_available" => :seats_available
  end

  scope "/bookings", controller: :bookings do
    post "/book" => :book, as: :book
    get "/search" => :search, as: :search_booking
    post "/" => :retrieve, as: :retrieve_booking
    get "/payment" => :payment, as: :payment
    post "/confirm" => :confirm, as: :confirm_book
    put "/:reference_number" => :update
    delete "/:reference_number" => :destroy
    get "/payment/:flight_id" => :validate_payment, as: :validate_payment
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Message
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def root_class
    if request.path == root_path
      "active item"
    else
      "item"
    end
  end

  def show_first_name
    text_field_content(:first_name, current_user)
  end

  def show_last_name
    text_field_content(:last_name, current_user)
  end

  def show_email
    text_field_content(:email, current_user)
  end

  def show_gender
    select_tag_content(current_user)
  end

  private

  def text_field_content(name, value = nil)
    placeholder = {
      first_name: "E.g John",
      last_name: "E.g Doe",
      email: "johndoe@gmail.com"
    }
    html_params = { placeholder: placeholder[name], required: true }
    value = value ? value.send(name) : nil
    text_field_tag("adult[][#{name}]", value, html_params)
  end

  def select_tag_content(value = nil)
    html_params = { class: "ui fluid dropdown" }
    value = value ? value.gender : nil
    options = options_for_select([%w(Male Male), %w(Female Female)], value)
    select_tag(:gender, options, html_params)
  end
end

app/views/application/_footer.html.erb
<section id="footer">
  <div class="ui black inverted vertical segment">
    <div class="ui center aligned container">
      <%= link_to root_path, class: 'item' do %>
        &copy; Fly Safe 2016
      <% end %>
    </div>
  </div>
</section>

app/views/application/_header.html.erb
<div class="ui small inverted menu">
  <%= link_to 'Home', root_path, class: root_class %>
  <%= active_link_to 'Manage Bookings', search_booking_path, class_active: 'active item', class_inactive: 'item' %>
  <%= active_link_to 'About Us', about_path, class_active: 'active item', class_inactive: 'item' %>
  <%= active_link_to 'Contact Us', contact_path, class_active: 'active item', class_inactive: 'item' %>

  <div class="right menu">
    <%= render partial: "right_menu" %>
  </div>
</div>

app/views/application/_notice.html.erb
<% if notice %>
  <div class="ui inline nag">
    <span class="title">
      <%= notice %>
    </span>
    <i class="close icon"></i>
  </div>
<% end %>

app/views/application/_right_menu.html.erb
<% if current_user %>
  <div class="item">
    <%= "Welcome, "+current_user.first_name+" "+current_user.last_name %>
  </div>

  <%= link_to past_bookings_path, 'data-no-turbolink': true, class: 'item' do %>
    <div class="ui blue button">Past Bookings</div>
  <% end %>
  <%= link_to logout_path, 'data-no-turbolink': true, class: 'item' do %>
    <div class="ui teal button">Logout</div>
  <% end %>
<% else %>
  <%= link_to signup_path, class: 'item' do %>
    <div class="ui primary button">Sign Up</div>
  <% end %>

  <%= link_to login_path, class: 'item' do %>
    <button class="ui teal button">Login</button>
  <% end %>
<% end %>